import { keccak256, stringToBytes, type Hex } from "viem";

/** One input the merchant needs from a buyer (e.g. email, shipping address). */
export interface FulfillmentField {
  /** Key used in the encrypted payload JSON. */
  name: string;
  /** Label shown on the checkout form. */
  label: string;
  type: "text" | "email" | "textarea";
  required: boolean;
  placeholder?: string;
}

/**
 * store.config.json — generated by the Launcher, human-editable for copy/images.
 * Product metadata and the fulfillment schema live only here (on-chain proof, in-config data);
 * price/token/pubkey are read live from the contract, with the values here used for instant
 * first paint.
 */
export interface StoreConfig {
  version: 1;
  chainId: number;
  /** Optional RPC override; defaults to the chain's public RPC. Never a secret. */
  rpcUrl?: string;
  storeAddress: Hex;
  product: {
    name: string;
    description: string;
    /** Repo-relative paths, https URLs, or IPFS gateway URLs. */
    images: string[];
  };
  payment: {
    /** address(0) sentinel for native ETH, else the store's ERC-20. */
    token: Hex;
    symbol: string;
    decimals: number;
    /** Price in base units, as a decimal string. */
    price: string;
  };
  fulfillment: {
    fields: FulfillmentField[];
  };
}

/**
 * Canonical hash of a fulfillment schema, committed on-chain at store deploy so buyers can
 * verify the form they see matches what the merchant registered. Canonical form is the exact
 * JSON.stringify of the fields array — the Launcher must generate config files with fields in
 * the same order it hashed them.
 */
export function hashFulfillmentSchema(fields: FulfillmentField[]): Hex {
  return keccak256(stringToBytes(JSON.stringify(fields)));
}

const FIELD_TYPES = new Set(["text", "email", "textarea"]);
const HEX_ADDRESS = /^0x[0-9a-fA-F]{40}$/;

/** Runtime validation for a fetched store.config.json. Throws with a readable message. */
export function parseStoreConfig(raw: unknown): StoreConfig {
  const fail = (msg: string): never => {
    throw new Error(`invalid store.config.json: ${msg}`);
  };
  if (typeof raw !== "object" || raw === null) fail("not an object");
  const cfg = raw as Record<string, any>;

  if (cfg.version !== 1) fail("version must be 1");
  if (!Number.isInteger(cfg.chainId) || cfg.chainId <= 0) fail("chainId must be a positive integer");
  if (cfg.rpcUrl !== undefined && typeof cfg.rpcUrl !== "string") fail("rpcUrl must be a string");
  if (typeof cfg.storeAddress !== "string" || !HEX_ADDRESS.test(cfg.storeAddress)) {
    fail("storeAddress must be a 0x address");
  }

  const product = cfg.product;
  if (typeof product?.name !== "string" || product.name.length === 0) fail("product.name required");
  if (typeof product.description !== "string") fail("product.description must be a string");
  if (!Array.isArray(product.images) || product.images.some((i: unknown) => typeof i !== "string")) {
    fail("product.images must be an array of strings");
  }

  const payment = cfg.payment;
  if (typeof payment?.token !== "string" || !HEX_ADDRESS.test(payment.token)) fail("payment.token must be a 0x address");
  if (typeof payment.symbol !== "string" || payment.symbol.length === 0) fail("payment.symbol required");
  if (!Number.isInteger(payment.decimals) || payment.decimals < 0 || payment.decimals > 36) {
    fail("payment.decimals must be an integer 0-36");
  }
  if (typeof payment.price !== "string" || !/^\d+$/.test(payment.price)) {
    fail("payment.price must be a base-unit decimal string");
  }

  const fields = cfg.fulfillment?.fields;
  if (!Array.isArray(fields) || fields.length === 0) fail("fulfillment.fields must be a non-empty array");
  const seen = new Set<string>();
  for (const f of fields) {
    if (typeof f?.name !== "string" || f.name.length === 0) fail("every fulfillment field needs a name");
    if (seen.has(f.name)) fail(`duplicate fulfillment field: ${f.name}`);
    seen.add(f.name);
    if (typeof f.label !== "string" || f.label.length === 0) fail(`field ${f.name}: label required`);
    if (!FIELD_TYPES.has(f.type)) fail(`field ${f.name}: type must be one of ${[...FIELD_TYPES].join(", ")}`);
    if (typeof f.required !== "boolean") fail(`field ${f.name}: required must be boolean`);
    if (f.placeholder !== undefined && typeof f.placeholder !== "string") {
      fail(`field ${f.name}: placeholder must be a string`);
    }
  }

  return cfg as StoreConfig;
}

/** The native-ETH sentinel used by StoreEscrow.paymentToken. */
export const ETH_SENTINEL: Hex = "0x0000000000000000000000000000000000000000";
