// Copies contract ABIs from the Foundry build output into packages/shared/abis/ (JSON) and
// generates src/abis.ts (`as const` for viem type inference).
// Run `forge build --root contracts` first (or `pnpm contracts:build` at the repo root).
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const outDir = join(repoRoot, "contracts", "out");
const sharedDir = join(repoRoot, "packages", "shared");

const contracts = ["StoreEscrow", "StorefrontFactory"];

await mkdir(join(sharedDir, "abis"), { recursive: true });
let ts = "// Generated by scripts/export-abis.mjs — do not edit.\n";
for (const name of contracts) {
  const artifact = JSON.parse(await readFile(join(outDir, `${name}.sol`, `${name}.json`), "utf8"));
  await writeFile(join(sharedDir, "abis", `${name}.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
  const varName = name[0].toLowerCase() + name.slice(1) + "Abi";
  ts += `\nexport const ${varName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  console.log(`exported ${name} (${artifact.abi.length} entries)`);
}
await writeFile(join(sharedDir, "src", "abis.ts"), ts);
